name=Cocol2Extractor
atg=$name.atg

mkdir temp

cp Coco-2/* temp/
cp $atg temp/
cd temp/

./PGT.exe $atg
./SG.exe $atg

sed "s/???/${name}/g" Main.frm > ${name}Main.cs
sed -i -e 1,7d ${name}Main.cs

cp ${name}Lex.cs ${name}Sem.cs ${name}Syn.cs ${name}Main.cs Utils.cs Errors.cs Sets.cs ../src/ExtractCocol2/CocolExtractor/autogenerated

cd ..
rm -rf temp
