name=Cocol2Extractor
atg=$name.atg

mkdir temp

cp Coco-2/* temp/
cp $atg temp/
cd temp/

./PGT.exe $atg
./SG.exe $atg

# create Main.cs
sed "s/???/${name}/g" Main.frm > ${name}Main.cs
sed -i -e 1,7d ${name}Main.cs

# add imports to ${name}Sem.cs
sed -i \
    -e "7iusing autosupport_lsp_server.Symbols;" \
    -e "7iusing autosupport_lsp_server.Symbols.Impl;" \
    -e "7iusing autosupport_lsp_server.Symbols.Impl.Terminals;" \
    -e "8iusing System.Collections.Generic;" ${name}Sem.cs

cp ${name}Lex.cs ${name}Sem.cs ${name}Syn.cs ${name}Main.cs Utils.cs Errors.cs Sets.cs ../src/ExtractCocol2/CocolExtractor/autogenerated

cd ..
rm -rf temp
