name=Cocol2Extractor
atg=$name.atg

mkdir temp

cp Coco-2/* temp/
cp $atg temp/
cd temp/

./PGT.exe $atg
./SG.exe $atg

cp ${name}Lex.cs ${name}Sem.cs ${name}Syn.cs Utils.cs Errors.cs Sets.cs ../src/ExtractCocol2/CocolExtractor/autogenerated

cd ..
rm -rf temp
